scw/errors.go, scw/errors_test.go, scw/request.go
Changed visibility of this types to be able to cast an error to this type and thus getting the status code.
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
=> feat: change visibility of errorResponse struct

scw/client.go, scw/client_option.go, scw/client_test.go, scw/request.go, scw/settings.go, scw/settings_test.go
Implemented three new `ClientOption`:
- `WithDefaultOrganizationId` client option sets the client default organization ID.  
It will be used as the default value of the organization_id field in all requests made with this client.
- `WithDefaultRegion` client option sets the client default region.  
It will be used as the default value of the region field in all requests made with this client.
- `WithDefaultZone` client option sets the client default zone.  
It will be used as the default value of the zone field in all requests made with this client.
=> feat: implement default field ClientOptions

internal/parameter/query.go
Fix bug for when a pointer is not initialized
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
=> fix: compare nil value with reflect.Value.IsNil

README.md, api/instance/v1/instance_sdk.go, api/lb/v1/lb_sdk.go, example_test.go, internal/testhelpers/test_helpers.go, scw/client.go, scw/client_option.go, scw/client_test.go, scw/request_test.go, scw/settings.go, scwconfig/config.go, scwconfig/config_test.go, utils/locality.go
- Implement a `func WithConfig(config scwconfig.Config) ClientOption` to configure a client with Scaleway configuration.
- Move `scw.{Region|Zone}` to `utils` package.
=> feat: implement WithConfig client option

api/instance/v1/instance_sdk.go, api/lb/v1/lb_sdk.go, internal/marshaler/body_marshaler.go, scw/request.go
Fix #24 
Content length was not set in default request. It was using a custom Reader (internal/marshaler.Body) which is not known by [http.NewRequest](https://golang.org/src/net/http/request.go?s=26724:26793#L834), causing the request to have no ContentLength.
=> Fix: content length

scw/errors.go, scw/errors_test.go
Improve Http error string message:
```
panic: http request [GET https://api.scaleway.com/instance/v1/zones/fr-par-1/servers?organization=] return [400 Bad Request]
{
"message": "Validation Error",
"type": "invalid_request_error",
"fields": {
"organization": [
" is not a valid UUID."
]
}
}
```
=> style: better http error message

api/instance/v1/instance_sdk.go, api/lb/v1/lb_sdk.go, scw/client.go, scw/client_option.go, scw/client_test.go, scw/settings.go, scw/settings_test.go
**This changes will break the public API.**
This PR refactor clients options getters. From now, they will return their values and a boolean that precise if the value has been set or not (with a `scw.WithDefaultSomething()`).
```golang
--- func (c *Client) GetDefaultOrganizationID() string
+++ func (c *Client) GetDefaultOrganizationID() (string, bool)
--- func (c *Client) GetDefaultRegion() utils.Region
+++ func (c *Client) GetDefaultRegion() (utils.Region, bool)
--- func (c *Client) GetDefaultZone() utils.Zone
+++ func (c *Client) GetDefaultZone() (utils.Zone, bool)
```
=> refactor: client getters

api/instance/v1/instance_sdk.go
- AltNames was not the correct type in proto
- PerVolumeConstraint is not a map as 100% of server type have an object with `l_ssd` key.
=> feat: update generated apis

api/k8s/v1beta3/k8s_helpers.go
=> feat: add k8s WaitForCluster method

strcase/bash_arg.go, strcase/bash_arg_test.go, strcase/goname.go, strcase/goname_test.go, strcase/strcase_test.go
- ToPublicGoName: convert a field name to a valid public Go name
- ToPrivateGoName: convert a field name to a valid private Go name
- ToBashArg: convert a field name to a valid bash argument
=> feat: add strcase lib

scw/config.go, scw/config_test.go
Usage example:
```go
// Get Scaleway config active profile
config, _ := scw.LoadConfig()
configProfile, _ := config.GetActiveProfile()
// Get Scaleway env active profile
envProfile := scw.LoadEnvProfile()
// Get flag values
flagProfile := &scw.Profile{
DefaultOrganizationID: scw.StringPtr("f121706b-2091-429b-a93a-c41b8ef4a068"),
}
// Merge profiles
profile := scw.MergeProfiles(configProfile, envProfile, flagProfile)
// Make custom validation or other stuff here...
// Create a Scaleway client
client, _ = scw.NewClient(scw.WithProfile(profile))
```
=> feat(core): add scw.MergeProfiles command

api/baremetal/v1alpha1/server_utils.go
Split `WaitForServer` into two methods:
- `WaitForServer`: waits for server creation.
- `WaitForServerInstall` waits for server installation.
Fix status:
- `ServerStatusUndelivered` means "delivering" so it is not a terminal state.
- `ServerInstallStatusToInstall` means "ready to start an installation" so it is not a terminal state either.
=> feat(baremetal): fix WaitForServer and add WaitForServerInstall

api/account/v2alpha1/account_sdk.go, api/baremetal/v1alpha1/baremetal_sdk.go, api/baremetal/v1alpha1/server_utils.go, api/instance/v1/instance_sdk.go, api/instance/v1/instance_utils.go, api/k8s/v1beta3/k8s_sdk.go, api/lb/v1/lb_sdk.go, api/marketplace/v1/marketplace_sdk.go, api/rdb/v1/rdb_sdk.go, api/registry/v1/registry_sdk.go, api/registry/v1/registry_utils.go, api/test/v1/test_sdk.go, internal/e2e/errors_test.go, scw/client.go, scw/errors.go, scw/errors_test.go, scw/request.go, scw/request_option.go
`+ fix: always return error interface`
=> feat(core): handle non standard errors

scw/errors.go, scw/errors_test.go
Converssions:
* Error type `invalid_request_error` with `fields` field => `InvalidArgumentsError`
* Error type `invalid_request_error` without `fields` field and with `message` field => `ResponseError`
* Error type `conflict` => `ResponseError`
See `errors_test.go` for more details.
=> feat(core): support more instance error types

scw/custom_types.go, scw/custom_types_test.go
=> feat(core): add String method to scw.Money

api/k8s/v1beta4/k8s_helpers.go
Requirement of https://github.com/terraform-providers/terraform-provider-scaleway/pull/393
=> feat(k8s): add WaitForPool & WaitForClusterPools helper methods

api/k8s/v1beta4/k8s_helpers.go
Removal of this methods since the usecase is no longer wanted and should be implemented on the client side
=> fix(k8s): remove WaitForClusterPools

.github/workflows/pull-request.yaml
Go 1.10 and 1.11 are not supported anymore, so removing them from github action tests
=> chore: remove go 1.10 and 1.11 from gh action

.github/workflows/pull-request.yaml
Downloading Go module explicitly seems useless as `go test` already download needed modules.
=> chore: remove module downloading step in test jobs

api/baremetal/v1alpha1/server_utils.go
This PR adds helper functions that help convert a commercial name such as `GP-BM1-M` with a matching offer id. It also adds the reciprocate function that from an OfferID returns the name.
This is useful in the usage of the CLI where a customer wants to order a bare-metal instance from the commercial name and not from the OfferID (which is a UUID)
=> feat(baremetal): add GetServerOffer and GetOfferFromName

api/k8s/v1beta4/k8s_helpers.go
=> fix(k8s): add global retry interval for wait func

api/baremetal/v1alpha1/server_utils.go
=> feat(baremetal): add RetryInterval variable

api/k8s/v1/k8s_helpers.go, api/k8s/v1/kubeconfig.go
=> feat(k8s): add kubeconfig and helpers to v1

api/baremetal/v1/server_utils.go
copy and pasted from the `v1alpha1` folder
=> feat(baremetal): add server helpers func in v1

api/iot/v1beta1/iot_helpers.go
Signed-off-by: Clément Decoodt <cdecoodt@online.net>
This is highly inspired from k8s product WaitForCluster, adapted for IoT Hubs
=> feat(iot): add WaitForHub IoT helper

api/instance/v1/instance_metadata_sdk.go
**This MR introduce a breaking change.**
Job done:
- Adds 3 new `Project` fields
- Remove `Post`, `Email` and `UserAgent` fields. It is already effective in the API and has already been announced on [the changelog](https://www.scaleway.com/en/changelog/?date=7-2020) and [a status](https://status.scaleway.com/incident/903).
=> feat(instance): update metadata struct

README.md, example_test.go, scw/README.md, scw/config.go, scw/config_test.go
=> doc(core): update credentials links

scw/convert.go, scw/custom_types_test.go
This method don't need to be deprecated since we rely on `*time.Duration` for `WaitFor` timeouts.
=> chore(scw): undeprecate TimeDurationPtr

internal/parameter/query.go
ip was handled as a uint8 slice
=> fix: convert ip to string when adding to query argument

example_test.go, internal/generic/sort.go, internal/generic/sort_test.go, scw/client.go, scw/request.go, scw/request_option.go
Complete region
```go
servers, err := api.ListServers(&instance.ListServersRequest{},
scw.WithZones(scw.RegionFrPar.GetZones()...),
)
```
Specific zones
```go
servers, err := api.ListServers(&instance.ListServersRequest{},
scw.WithZones(scw.ZoneFrPar1, scw.ZoneFrPar2, scw.ZoneNlAms1),
)
```
All zones
```go
servers, err := api.ListServers(&instance.ListServersRequest{},
scw.WithZones(scw.AllZones...),
)
```
=> feat(client): add WithZones and WithRegions options

api/k8s/v1/k8s_helpers.go
this fixes [issue#1468](https://github.com/scaleway/scaleway-sdk-go/issues/1468)
=> fix(k8s): no more crashes on waiting helpers

logger/default_logger.go
Debug = 0
Warning = 2
With level as Warning, `logger.ShouldLog(Debug)` returned true, it should return false
`Debug <= Warning` is true (wrong)
`Debug >= Warning` is false (good)
=> fix(core): logger shouldLog checking lower log level

scw/client.go, scw/client_test.go
Current cli because of this:
```
± scw --debug instance server get ee7bd9e1-9cbd-4724-b2f4-19e50f3cf38b
--------------- Scaleway SDK REQUEST 1 : ---------------
GET /instance/v1/zones/fr-par-1/servers/ee7bd9e1-9cbd-4724-b2f4-19e50f3cf38b HTTP/1.1
Host: api.scaleway.com
User-Agent: scaleway-sdk-go/v1.0.0-beta.7+dev (go1.19.3; linux; amd64) scaleway-cli/2.0.0+dev
Accept-Encoding: gzip
---------------------------------------------------------
--------------- Scaleway SDK REQUEST 1 : ---------------
GET /instance/v1/zones/fr-par-1/servers/ee7bd9e1-9cbd-4724-b2f4-19e50f3cf38b HTTP/1.1
Host: api.scaleway.com
User-Agent: scaleway-sdk-go/v1.0.0-beta.7+dev (go1.19.3; linux; amd64) scaleway-cli/2.0.0+dev
Accept-Encoding: gzip
---------------------------------------------------------
```
=> fix(core): nested logger transport when creating multiple clients

api/vpcgw/v1/vpcgw_utils.go
When creating a gateway network it will do `created` -> `attaching` -> `ready`
The two status before `ready` are transient status
=> fix(vpcgw): gateway network terminal status

scw/client.go, scw/errors.go
=> fix(client): validate content-type starting with json

api/marketplace/v2/marketplace_utils.go
This is a newly added filter, it is needed so that other devtools are prepared for its usage.
It split images between old images on instance and new ones that will be on SBS api
=> feat(marketplace): add type filter to GetLocalImageByLabel

scw/client.go
This PR aims to allow usage of an HTTP proxy to communicate with the Scaleway API.
In order to keep this feature simple and standard, I suggest to use the function [ProxyFromEnvironment](https://pkg.go.dev/net/http#ProxyFromEnvironment) from the package `net/http`.
=> feat(scw): allow usage of http proxy

api/k8s/v1/k8s_helpers.go
As they finish creation, Dedicated Control-Plane clusters' status is `ready` when in Kapsule clusters it's `pool_required`. This causes the WaitForCluster function to timeout at creation with these types of clusters because the WaitForPool function that it calls only considers `pool_required` to be the sign that the cluster is ready.
=> fix(k8s): add ready to terminal statuses for DCP clusters

internal/parameter/query.go
Before : `?contains=%7B%7B0.0.0.0+00000000%7D%7D`
After: `?contains=0.0.0.0/0`
=> fix(internal): fix net.IPNet and scw.IPNet in query param

internal/parameter/query.go
`time.Time` does not exist in query parameters.
It could exist in a List Request but I couldn't find any. 
Used regex: `[^}]List.*Request struct \{(\s|.)*? \*time\.Time(\s|.)*?}`, remove star before time.Time for non-pointer ones.
=> fix: time ptr query parameter

scw/client.go
=> fix: use default http transport

scw/transport.go
This new identifier helps reading large logs of debug mode. Multiple clients in parallel would log multiple requests with the same request number.
=> feat: add unique identifier to logged requests

scw/errors.go, scw/errors_test.go
=> chore(errors): remove toLower conversion for API error messages

scw/client.go
When an HTTP response body is empty we should not try to read/unmarshal it.
=> fix: don't try to read/unmarshal response content when empty

scw/client.go
From go doc:
```
// ContentLength records the length of the associated content. The
// value -1 indicates that the length is unknown. Unless Request.Method
// is "HEAD", values >= 0 indicate that the given number of bytes may
// be read from Body.
```
Some requests may have -1 as content-length and still have a body that we must read. A long list response received chunked for example.
=> fix(scw): read body with unknown content-length

scw/config.go, scw/config_test.go
Avoid panic if loading a config with an empty profile, from the CLI
```
➜  scaleway-cli git:(master) ✗ SCW_CLI_CONFIG_PATH="./my_cfg.yml" go run ./cmd/scw/main.go  login -p test
waiting for callback from browser...
@@@@@@@@@@@@@@@.
@@@@@@@@@@@@@@@@@@@@        __          __  _
@@@               @@@@      \ \        / / | |
@@@    @@@@@@@     .@@@      \ \  /\  / /__| | ___ ___  _ __ ___   ___
@@@   @@@@@@@@      @@@       \ \/  \/ / _ \ |/ __/ _ \| '_ ` _ \ / _ \
@@@   @@@           @@@        \  /\  /  __/ | (_| (_) | | | | | |  __/
@@@   @@@     @@@   @@@         \/  \/ \___|_|\___\___/|_| |_| |_|\___|
@@@   @@@     @@@   @@@                                         _  _
@@@           @@@   @@@                                        | |(_)
@@@      .@@@@@@@   @@@             ___   ___ __ …
```
=> fix(scw): config.String() panic with an empty profile

api/instance/v1/server_utils.go, api/instance/v1/server_utils_test.go, api/instance/v1/testdata/create-server-image-label-resolution.yaml
This PR fixes the image label resolution. By first determining the type of volume on which the instance will boot, we ensure that the image fetched from the marketplace is compatible with the volume.
Closes #2603
=> fix(instance): resolve image label according to boot volume type

api/vpc/v2/vpc_utils.go
A lot of tests involving Private Networks are currently failing because of the same error (code 500) that occurs when attempting to delete a PN which state is still transient. 
The VPC API does not disclose the state of the resource, so we can't implement a proper waiter function, but we should at least have a function that retries a few times to delete the resource as long as the error code is 500. 
We could then call this function both in Terraform and in the CLI to fix a good proportion of the nightly tests.
=> feat(vpc): add retry function when deleting private networks
