scaleway/scaleway-sdk-go

scw/request.go

For now there is a single request option: `WithContext`

feat: apply request option

---

api/instance/v1/instance_sdk.go
api/lb/v1/lb_sdk.go

* support default zone/region/organizationID client options

feat: update generated apis

---

utils/locality.go

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

feat: add list of regions and zones

---

README.md
api/instance/v1/instance_sdk.go
api/lb/v1/lb_sdk.go
api/marketplace/v1/marketplace_sdk.go
api/marketplace/v1/marketplace_utils.go
api/marketplace/v1/marketplace_utils_test.go
example_test.go

fix: go lint generated files

---

api/instance/v1/instance_sdk.go
api/lb/v1/lb_sdk.go
api/marketplace/v1/marketplace_sdk.go
scw/client.go
scw/client_option.go
scw/client_test.go
scw/settings.go

feat: implement client.WithDefaultPageSize

---

scw/lister.go

Fixes #70 
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

fix: check zero page size for pagination

---

api/instance/v1/server_utils.go

feat: add instance.WaitForServer

---

MAINTAINERS.md

Thanks for your help @DenBeke! 🎉

doc: remove DenBeke from maintainers

---

api/k8s/v1beta4/k8s_helpers.go
api/k8s/v1beta4/kubeconfig.go

fix(k8s): copy helpers from v1beta3 to beta4

---

api/instance/v1/instance_sdk.go
api/instance/v1/instance_utils.go
api/lb/v1/lb_sdk.go

chore: replace AttachIp() and DetachIP() by UpdateIP()

---

api/k8s/v1beta4/k8s_helpers.go

fix(k8s): add default timeout to wait methods

---

.github/workflows/pull-request.yaml

This PR adds GitHub actions in order to test the reliability of the solution for a few months 

chore: add github action for PR testing

---

api/k8s/v1beta4/k8s_helpers.go

fix(k8s): make WaitForPool(s) coherent with others

---

.github/workflows/pull-request.yaml

chore(core): add windows and macos build tests

---

scripts/release/package.json
scripts/release/release.js
scripts/release/yarn.lock

Small refactor of the release script to:
- Open an editor to edit changelog before it is committed
- Automatically open browser to create PR
- Automatically open browser with pre-filled info to create release

chore: update release script

---

api/lb/v1/lb_sdk.go

feat(lb): add SSL compatibility level

---

api/k8s/v1beta4/k8s_helpers.go

feat(k8s): add wait for node method

---

api/k8s/v1beta4/kubeconfig.go

fix(k8s): change type for kubeconfig certificates

---

api/k8s/v1/k8s_helpers.go

fix(k8s): panic on helpers timeout

---

scw/errors.go
scw/errors_test.go

fix(errors): handle all instance not found return messages

---

sdk_compilation_test.go

Signed-off-by: Clément Decoodt <cdecoodt@online.net>

chore(sdk_compilation_test): add missing api packages in test

---

scw/locality.go

- Log info unknown zone
- Stringer interface on zone / region types

chore(locality): small fixes

---

scw/errors.go
scw/errors_test.go

fix: handle additional non standards errors

---

scw/README.md

We will need to update all credential links, it will be done in another PR.

doc(config): add project_id

---

scw/errors.go

feat(errors): add PreconditionFailed and DeniedAuthentication to std errs

---

api/instance/v1/instance_metadata_sdk.go

feat(instance): add private network to instance metadata

---

scripts/release/package.json
scripts/release/yarn.lock

```bash
yarn upgrade git-raw-commits@2.0.9
```

fix: security warning on yarn dependency

---

api/iot/v1/iot_helpers.go

We wait for the api v1 to be deployed before merging this PR.

feat(iot): add api v1 support

---

api/instance/v1/security_group_utils_test.go
scw/custom_types.go
scw/custom_types_test.go

- fix(custom_types): ipnet unmarshal json
- Revert "fix(custom_types): ipnet unmarshal json"
- fix(custom_types): ipnet unmarshal json

fix(ipnet): add ip to unsmarshall and test

---

api/k8s/v1/k8s_helpers.go

- Remove stable state from cluster
- Create waiting method to pool association

feat(k8s): add waiting for k8s cluster pool

---

strcase/goname.go

This reverts commit f550579b1e4732cb7dc26a547095afba032c9760.

Revert "feat(strcase): update common initialisms (#1274)"

---

scw/config.go
scw/config_test.go

feat(scw): try to read yaml file as yml on fail

---

internal/auth/token.go
scw/client.go
scw/client_test.go
scw/transport.go

feat(core): move request logging from client to a transport

---

scw/client.go

Some lister start to appear with uint64 type, changing generation to use uint64 in lister interface
If fixed some namespaces manually as they are no longer or were never generated

fix(core): change lister to uint64

---

api/instance/v1/instance_utils.go

Needs an update of generation to add `total_count`
Needed to fix https://github.com/scaleway/scaleway-cli/issues/3189

feat(instance): implement lister for GetServerTypesAvailability

---

scw/config.go
scw/config_test.go

docs: update config template credentials url

---

api/block/v1alpha1/volume_utils.go
api/instance/v1/instance_utils.go
api/instance/v1/instance_utils_test.go
api/instance/v1/testdata/utils-test-block.yaml
api/instance/v1/volume_utils.go

Removed IP tests as it was not testing helpers, also it was not valid anymore as it is using an invalid reverse.

fix: instance helpers with new block volumes

---

api/instance/v1/instance_metadata_sdk.go

Add ipv6 api metadata to improve ip mobility support. 
Basic implementation to avoid breaking change of instance.NewMetadataAPI() signature.

feat(instance): add ipv6 metadata

---

api/rdb/v1/rdb_utils.go

fix(rdb): add InstanceLogId in GetInstanceLogRequest

---

api/applesilicon/v1alpha1/apple_silicon_utils.go

feat(apple-silicon): add WaitForPossibleServerDeletion support

---

scw/client.go
scw/version.go

fix(scw): get user-agent from debug info

---

api/container/v1beta1/testdata/container-list-regions.yaml

This PR fixes the tests that were currently failing in the container scope.

tests(container): update cassette for TestListContainerNamespaceMultipleRegions

---

api/instance/v1/instance_sdk_server_test.go
api/instance/v1/instance_utils_test.go
api/instance/v1/security_group_utils_test.go
api/instance/v1/server_utils_test.go
api/instance/v1/snapshot_utils_test.go
api/instance/v1/testdata/create-server.yaml
api/instance/v1/testdata/security-group-rule-test.yaml
api/instance/v1/testdata/security-group-test.yaml
api/instance/v1/testdata/snapshot-test.yaml
api/instance/v1/testdata/utils-test-block.yaml
api/instance/v1/volume_utils_test.go

This PR fixes the tests that were currently failing in the instance scope.

tests(instance): update failed tests

---

api/iam/v1alpha1/iam_sdk.go

feat(iam): deprecate `UserStatus`
